name: CI

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
    tags: ['*']
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PNPM
        uses: pnpm/action-setup@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --silent --frozen-lockfile --prefer-offline --prod=false

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm tsc

      - name: Start testing environment
        run: |
          export $(grep -v '^#' .env | xargs)
          docker run -d --name fwxs -p 5432:5432 -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=fwxs postgres:18-alpine
          timeout 10 bash -c -- "while ! docker run --rm --network=host -i postgres:18-alpine pg_isready --quiet --timeout=1 -d postgres://user:password@localhost:5432/fwxs; do sleep 1; done"

      - name: Test
        run: pnpm test

  release:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    if: startsWith(github.ref, 'refs/tags/')
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PNPM
        uses: pnpm/action-setup@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: pnpm publish --no-git-checks
